[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mobile-price-range"
version = "0.1.0"
description = "Mobile price-range prediction package"
authors = [ { name = "You" } ]
dependencies = [
  "pandas",
  "scikit-learn",
  "joblib",
  "streamlit",
  "pyyaml"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
